{ ... }: {
  autogenerated = 0; # remove this line to remove the warning

  # See https://wiki.hyprland.org/Configuring/Monitors/
  # monitor=,preferred,auto,1
  monitor = [
    "eDP-1,1920x1080@60,0x0,1"
    "DP-1,transform,1"
    "DP-1,2560x1440@75,1920x0,1"
  ];
  # workspace = [
  #   "DP-1,1"

  # ]; 
  # See https://wiki.hyprland.org/Configuring/Keywords/ for more

  # Execute your favorite apps at launch
  exec-once = "hyprpaper"; #& nm-applet 
  # exec-once gsettings set org.gnome.desktop.interface gtk-theme Arc-Dark
  # exec-once gsettings set org.gnome.desktop.interface gtk-theme Arc-Dark


  # Some default env vars.
  env = [
    "XCURSOR_SIZE,12"
    "GDK_SCALE,1"
  ];

  # For all categories, see https://wiki.hyprland.org/Configuring/Variables/
  input = {
      kb_layout = "au";
      # kb_variant =
      # kb_model =
      # kb_options =
      # kb_rules =

      follow_mouse = 1;

      touchpad = {
          natural_scroll = "no";
      };

      sensitivity = 0.5; # -1.0 - 1.0, 0 means no modification.
  };

  general = {
      # See https://wiki.hyprland.org/Configuring/Variables/ for more

      gaps_in = 5;
      gaps_out = 5;
      border_size = 2;
      "col.active_border" = "rgba(DD6418ee) rgba(BE0E18ee) 25deg";
      "col.inactive_border" = "rgba(595959aa)";

      layout = "dwindle";
  };

  decoration = {
      # See https://wiki.hyprland.org/Configuring/Variables/ for more

      rounding = 3;
      # blur = yes;
      # blur_size = 3;
      # blur_passes = 1;
      # blur_new_optimizations = on;

      drop_shadow = true; # yes
      shadow_range = 4;
      shadow_render_power = 3;
      "col.shadow" = "rgba(1a1a1aee)";
  };

  animations = {
      enabled = true; # yes

      # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

      bezier = "myBezier, 0.05, 0.9, 0.1, 1.05";

      animation = [
        "windows, 1, 4, myBezier"
        "windowsOut, 1, 5, default, popin 80%"
        "border, 1, 5, default"
        "borderangle, 1, 6, default"
        "fade, 1, 4, default"
        "workspaces, 1, 4, default"
      ]; 
  };

  dwindle = {
      # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
      pseudotile = true; # yes master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
      preserve_split = true; # yes you probably want this
  };

  master = {
      # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
      new_is_master = true;
  };

  gestures = {
      # See https://wiki.hyprland.org/Configuring/Variables/ for more
      workspace_swipe = true;
  };

  # Example per-device config
  # See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
  # device:epic mouse V1 {
  #     sensitivity = -0.5
  # }

  # Example windowrule v1
  # windowrule = float, ^(kitty)$
  # Example windowrule v2
  # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
  # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


  # See https://wiki.hyprland.org/Configuring/Keywords/ for more
  "$mainMod" = "SUPER";

  # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
  bind = [
    "$mainMod, RETURN, exec, kitty"
    "$mainMod, Q, killactive,"
    "$mainMod, M, exit,"
    "$mainMod, E, exec, nemo"
    "$mainMod, V, togglefloating,"
    "$mainMod, D, exec, rofi -show combi -combi-modes 'window,drun,ssh' -modes combi"
    "$mainMod, P, pseudo," # dwindle
    "$mainMod, J, togglesplit," # dwindle
    "$mainMod, l, hyprexpo:expo, toggle" # can be: toggle, off/disable or on/enable

    # Move focus with mainMod + arrow keys
    "$mainMod, left, movefocus, l"
    "$mainMod, right, movefocus, r"
    "$mainMod, up, movefocus, u"
    "$mainMod, down, movefocus, d"

    # Switch workspaces with mainMod + [0-9]
    "$mainMod, 1, split-workspace, 1"
    "$mainMod, 2, split-workspace, 2"
    "$mainMod, 3, split-workspace, 3"
    "$mainMod, 4, split-workspace, 4"
    "$mainMod, 5, split-workspace, 5"
    "$mainMod, 6, split-workspace, 6"
    "$mainMod, 7, split-workspace, 7"
    "$mainMod, 8, split-workspace, 8"
    "$mainMod, 9, split-workspace, 9"
    "$mainMod, 0, split-workspace, 10"

    # Move active window to a workspace with mainMod + SHIFT + [0-9]
    "$mainMod SHIFT, 1, split-movetoworkspace, 1"
    "$mainMod SHIFT, 2, split-movetoworkspace, 2"
    "$mainMod SHIFT, 3, split-movetoworkspace, 3"
    "$mainMod SHIFT, 4, split-movetoworkspace, 4"
    "$mainMod SHIFT, 5, split-movetoworkspace, 5"
    "$mainMod SHIFT, 6, split-movetoworkspace, 6"
    "$mainMod SHIFT, 7, split-movetoworkspace, 7"
    "$mainMod SHIFT, 8, split-movetoworkspace, 8"
    "$mainMod SHIFT, 9, split-movetoworkspace, 9"
    "$mainMod SHIFT, 0, split-movetoworkspace, 10"

    # Scroll through existing workspaces with mainMod + scroll
    "$mainMod, TAB, split-workspace, e+1"
    "$mainMod SHIFT, TAB, split-workspace, e-1"
  ];  


  # Move/resize windows with mainMod + LMB/RMB and dragging
  bindm = [
    "$mainMod, mouse:272, movewindow"
    "$mainMod, mouse:273, resizewindow"
  ]; 
}